gauth:
  clientId:
  clientSecret:
  loginUrl:
  redirectUri: localhost:8080/auth/redirect
  authUrl: http://10.82.18.111:8080/

jwt:
  accessSecret: KOKQfwc4MW3KbrPlEf6+iokZs4I8glOQ/n9MYvtSAtA=
  refreshSecret: zeutC5iAJWdUoGtT3ls03twgpgXBvP6swJ5FFnaXD84=

spring:
  redis:
    host: localhost
    port: 6379
